version: '3'
networks:
  zookeeper_network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.11.0.0/16
services:
  redis:
    image: ljl763606865/redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ${HOME}/docker/redis/data:/data
      - ${HOME}/docker/redis/redis.conf:/etc/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 50M
    command:
      ['redis-server', '/etc/redis/redis.conf']
  mysql:
    image: ljl763606865/mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ${HOME}/docker/mysql/data:/var/lib/mysql
      - ${HOME}/docker/mysql/logs:/var/log/mysql
    deploy:
      resources:
        limits:
          memory: 600M
  mongo:
    image: ljl763606865/mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ${HOME}/docker/mongodb/db:/data/db
    deploy:
      resources:
        limits:
          memory: 500M
  rabbitmq:
    image: ljl763606865/rabbitmq
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ${HOME}/docker/rabbitmq/data:/var/lib/rabbitmq
      - ${HOME}/docker/rabbitmq/logs:/var/log/rabbitmq
  zookeeper:
    image: ljl763606865/zookeeper
    container_name: zookeeper_master
    ports:
      - "2181:2181"
    volumes:
      - ${HOME}/docker/mongodb/db:/data/db
      - ${HOME}/docker/zookeeper/master/conf/zoo.cfg:/conf/zoo.cfg
      - ${HOME}/docker/zookeeper/master/data:/data
      - ${HOME}/docker/zookeeper/master/datalog:/datalog 
      - ${HOME}/docker/zookeeper/master/logs:/logs
    restart: always
    environment:
      ZOO_MY_ID: 1
    networks:
      zookeeper_network:
        ipv4_address: 172.11.0.6
  kafka_master:
    image: ljl763606865/kafka
    container_name: kafka_master
    ports:
      - "9096:9096"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: 172.11.0.6:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.0.4.9:9096
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9096
    networks:
     - zookeeper_network
  php-fpm:
    image: ljl763606865/php-fpm
    container_name: php
    ports:
      - "9000:9000"
      - "9501:9501"
    volumes:
      - ${HOME}/docker-workspace/www/code:/var/www/html
      - ${HOME}/docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      TZ: Asia/Shanghai
    links:
      - redis
      - mysql
      - mongo
      - zookeeper
      - rabbitmq
    depends_on:
      - redis
      - mysql
      - mongo
      - zookeeper
      - rabbitmq
  nginx:
    image: ljl763606865/nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ${HOME}/docker-workspace/www/code:/var/www/html
      - ${HOME}/docker/nginx/conf:/etc/nginx/conf.d
      - ${HOME}/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - php-fpm
    depends_on:
      - php-fpm
